# Netlify設定ファイル

[build]
  # ビルドコマンド：環境変数からconfig.jsを生成
  command = "chmod +x build.sh && ./build.sh"

  # 公開ディレクトリ
  publish = "."

[build.environment]
  # Node.jsバージョン（必要に応じて）
  NODE_VERSION = "18"

# リダイレクト設定（SPAではないため不要）
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/config.js"
  [headers.values]
    # config.jsはキャッシュしない（環境変数の変更を即座に反映）
    Cache-Control = "no-cache, no-store, must-revalidate"
